apiVersion: 1

datasources:
  # PostgreSQL - Velib data warehouse
  - name: PostgreSQL
    uid: PBFA97CFB590B2093
    type: postgres
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false

  # Loki - Airflow logs
  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    editable: false
